### ISSUE TITLE
subprocess.py", line 1024, in _execute_child     raise child_exception OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MikhailovSergei** [DeepRNN/image_captioning#14]
Loading the model from ./models/289999.npy...
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:01<00:00, 23.69it/s]
47 tensors loaded.
Evaluating the model ...
batch: 100%|█████████████████████████████████████████████████████████████████████████████████| 1266/1266 [2:02:42<00:00,  5.83s/it]
Loading and preparing results...     
DONE (t=0.13s)
creating index...
index created!
tokenization...
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/home/viktor/anaconda2/envs/captureimage4/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 58, in main
    model.eval(sess, coco, data, vocabulary)
  File "/home/viktor/anaconda2/envs/captureimage4/scr/image_captioning-master/base_model.py", line 108, in eval
    scorer.evaluate()
  File "/home/viktor/anaconda2/envs/captureimage4/scr/image_captioning-master/utils/coco/pycocoevalcap/eval.py", line 31, in evaluate
    gts  = tokenizer.tokenize(gts)
  File "/home/viktor/anaconda2/envs/captureimage4/scr/image_captioning-master/utils/coco/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/home/viktor/anaconda2/envs/captureimage4/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/viktor/anaconda2/envs/captureimage4/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
(captureimage4) viktor@viktor-System-Product-Name:

**Comment by MikhailovSergei** [comment]
I solve it. Just reinstall my java.
