### ISSUE TITLE
You may need to pass the encoding= option to numpy.load

### ISSUE THREAD

**Issue by momodding** [DeepRNN/image_captioning#25]
i'm using mac os x el capitan
python 3.6.5
the last line error which given to me is 'You may need to pass the encoding= option to numpy.load'
log of process:
loading annotations into memory...
Done (t=4.42s)
creating index...
index created!
Filtering the captions by length...
creating index...
index created!
Building the vocabulary...
Vocabulary built.
Number of words = 5000
Filtering the captions by words...
creating index...
index created!
Processing the captions...
Captions processed.
Number of captions = 515671
Building the dataset...
Dataset built.
Building the CNN...
CNN built.
Building the RNN...
RNN built.
Loading the CNN from vgg16_no_fc.npy...
loading annotations into memory...
Done (t=3.82s)
creating index...
index created!
Filtering the captions by length...
creating index...
index created!
Building the vocabulary...
Vocabulary built.
Number of words = 5000
Filtering the captions by words...
creating index...
index created!
Processing the captions...
Captions processed.
Number of captions = 515671
Building the dataset...
Dataset built.
Building the CNN...
CNN built.
Building the RNN...
RNN built.
Loading the CNN from vgg16_no_fc.npy...

**Comment by dongxn20** [comment]
由于在Python2 中的默认编码为ASCII，但是在Python3中的默认编码为UTF-8。
所以在使用np.load(det.npy)的时候会出现错误提示：
you may need to pass the encoding= option to numpy.load
当遇到这种情况的时候，用np.load(det.npy,encoding="latin1")就可以了。

**Comment by momodding** [comment]
thanks. it worked
but after that I get error like this
Traceback (most recent call last):
  File "running.py", line 4, in <module>
    from setup import NNCaptioning
  File "/Users/momodding/Documents/image_captioning-master/setup.py", line 5, in <module>
    from model import CaptionGenerator
  File "/Users/momodding/Documents/image_captioning-master/model.py", line 4, in <module>
    from base_model import BaseModel
  File "/Users/momodding/Documents/image_captioning-master/base_model.py", line 11, in <module>
    from utils.nn import NN
ModuleNotFoundError: No module named 'utils.nn'

I can't find any utils.nn package

**Comment by TheRockXu** [comment]
> 由于在Python2 中的默认编码为ASCII，但是在Python3中的默认编码为UTF-8。
> 所以在使用np.load(det.npy)的时候会出现错误提示：
> you may need to pass the encoding= option to numpy.load
> 当遇到这种情况的时候，用np.load(det.npy,encoding="latin1")就可以了。

Works!

**Comment by abhisingh192** [comment]
> i'm using mac os x el capitan
> python 3.6.5
> the last line error which given to me is 'You may need to pass the encoding= option to numpy.load'
> log of process:
> loading annotations into memory...
> Done (t=4.42s)
> creating index...
> index created!
> Filtering the captions by length...
> creating index...
> index created!
> Building the vocabulary...
> Vocabulary built.
> Number of words = 5000
> Filtering the captions by words...
> creating index...
> index created!
> Processing the captions...
> Captions processed.
> Number of captions = 515671
> Building the dataset...
> Dataset built.
> Building the CNN...
> CNN built.
> Building the RNN...
> RNN built.
> Loading the CNN from vgg16_no_fc.npy...
> loading annotations into memory...
> Done (t=3.82s)
> creating index...
> index created!
> Filtering the captions by length...
> creating index...
> index created!
> Building the vocabulary...
> Vocabulary built.
> Number of words = 5000
> Filtering the captions by words...
> creating index...
> index created!
> Processing the captions...
> Captions processed.
> Number of captions = 515671
> Building the dataset...
> Dataset built.
> Building the CNN...
> CNN built.
> Building the RNN...
> RNN built.
> Loading the CNN from vgg16_no_fc.npy...

Hey, I'm also getting the same error 'You may need to pass the encoding= option to numpy.load', how did you resolve it
