### ISSUE TITLE
how can I use part of training data?

### ISSUE THREAD

**Issue by Brian0906** [DeepRNN/image_captioning#51]
If I just put some of the training data into the /images fold, there is always an error shown below.

Training the model...
epoch:   0%|                                            | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):                    | 0/11290 [00:00<?, ?it/s]
  File "main.py", line 72, in <module>
    tf.app.run()
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 53, in main
    model.train(sess, data)
  File "/Users/brian/Downloads/show-attend-and-tell-master/base_model.py", line 50, in train
    images = self.image_loader.load_images(image_files)
  File "/Users/brian/Downloads/show-attend-and-tell-master/utils/misc.py", line 34, in load_images
    images.append(self.load_image(image_file))
  File "/Users/brian/Downloads/show-attend-and-tell-master/utils/misc.py", line 18, in load_image
    temp = image.swapaxes(0, 2)
AttributeError: 'NoneType' object has no attribute 'swapaxes'

**Comment by Kinghup** [comment]
The problem is common, you need to check the train data folder. And it's sure the folder contains the imsges directly
