### ISSUE TITLE
Can not test the data

### ISSUE THREAD

**Issue by Pikkurthi** [DeepRNN/image_captioning#53]
Loading the model from ./models/289999.npy...
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 64, in main
    model.load(sess, FLAGS.model_file)
  File "/content/lstm_gru/image_captioning/base_model.py", line 262, in load
    data_dict = np.load(save_path).item()
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/format.py", line 650, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError

**Comment by Natalie00** [comment]
I met with the same problem. 

I set np.load(save_path, allow_pickle = True).item() in base_model.py. Then it runs successfully. However, I can‘t get test results. 

Have you fix the problem yet?

**Comment by Yeeef** [comment]
I have met this problem too and successfully fixed it just now.
The solution is simple yet naive - redownload the data, since you may downloaded a corrupted data like I used to do.
Besides, make sure that you use py2.7.

**Comment by I-NI** [comment]
> I met with the same problem.
> I set np.load(save_path, allow_pickle = True).item() in base_model.py. Then it runs successfully. However, I can‘t get test results.
> Have you fix the problem yet?

when i train the model, i meet the same problem, i have set the code as your advise, but it doesn't work
Loading the CNN from ./vgg16_no_fc.npy...
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/home/prj201800005/miniconda2/envs/mypython2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 48, in main
    model.load_cnn(sess, FLAGS.cnn_model_file)
  File "/media/sdb/Chen/deeplearning/LSTM/image_captioning/base_model.py", line 273, in load_cnn
    data_dict = np.load(data_path,allow_pickle=True).item()
  File "/home/prj201800005/miniconda2/envs/mypython2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/prj201800005/miniconda2/envs/mypython2/lib/python2.7/site-packages/numpy/lib/format.py", line 657, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError

**Comment by I-NI** [comment]
> I have met this problem too and successfully fixed it just now.
> The solution is simple yet naive - redownload the data, since you may downloaded a corrupted data like I used to do.
> Besides, make sure that you use py2.7.

is there a way to check the data? i download the val2014 from baidu netdisk, but dont know it is corrupted or not

**Comment by Yeeef** [comment]
> > I have met this problem too and successfully fixed it just now.
> > The solution is simple yet naive - redownload the data, since you may downloaded a corrupted data like I used to do.
> > Besides, make sure that you use py2.7.
> 
> is there a way to check the data? i download the val2014 from baidu netdisk, but dont know it is corrupted or not

I afraid not. Just try to re-download it or download it from [microsoft coco](http://cocodataset.org/#download)
